MSP430-overlay
==============

Creating a MSP430 cross-compile toolchain on Gentoo
---------------------------------------------------

1. Add this overlay to your Gentoo system. Use the command `layman -a msp430`
if you're already using layman to manage your overlays. See the
http://www.gentoo.org/proj/en/overlays/userguide.xml[overlay user guide]
for more information on overlay management with layman.

2. Install sys-devel/crossdev from this overlay which includes proper msp430
support.

3. Use the command `sudo crossdev --target msp430` to create a standard MSP430
toolchain. Note that you can also specify a specific version for any toolchain
package and if you want gdb support you should run `sudo crossdev --ex-gdb
msp430` instead. See `crossdev --help` for more information.

4. Once crossdev successfully creates a toolchain you should symlink the
ldscripts folder into a place where the linker will find it. If you don't do
this you may run into problems discussed in
http://bugs.gentoo.org/show_bug.cgi?id=147155[bug #147155], especially if
you're using flags specifying specific instruction sets. Running the command
`sudo ln -s /usr/$CHOST/msp430/lib/ldscripts /usr/msp430/lib/ldscripts` where
$CHOST is something like x86_64-pc-linux-gnu or i686-pc-linux-gnu for standard
amd64 or x86 architectures running Gentoo.
